# Execute the "targets" in this file with `make <target>` e.g., `make test`.
#
# You can also run multiple in sequence, e.g. `make clean lint test serve-coverage-report`


curr_dir: # Shows the current directory
	@bash fastapi_run.sh show_curr_dir