# Execute the "targets" in this file with `make <target>` e.g., `make test`.
#
# You can also run multiple in sequence, e.g. `make clean lint test serve-coverage-report`


curr_dir: # Shows the current directory
	@bash graphql_run.sh show_curr_dir

launch_server:
	@bash graphql_run.sh run_server